#!/usr/bin/perl
#
# verify - Verifies the contents of flash memory cards against original content.
#          OSAB - the Open Source Audio Bible player
#
# Copyright (C) 2012-2020 Theophilus (http://theaudiobible.org)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

use File::Copy;

if ($#ARGV < 0) {
    die "Usage: verify <device_name> <content_file> \n\nWhere: <device_name> is the name assigned to the device by the kernel (e.g. sdb)\n       <content_file> is the content index file that lists all the chapter files that were originally uploaded to the microSD card.\n";
}

my $kname = $ARGV[0];
my $chapfile = $ARGV[1];

#open(STDOUT, ">", "/tmp/$kname-stdout.txt")
#								or die "cannot open /tmp/$kname-stdout.txt: $!";
#open(STDERR, ">", "/tmp/$kname-stderr.txt")
#								or die "cannot open /tmp/$kname-stderr.txt: $!";

if (! -e $chapfile) {
    die "$chapfile does not exist.  $!";
}

$mounted = `grep $kname /etc/mtab`;

if ($mounted) {
    print "/dev/$kname is mounted.\n";
    print "Unmounting /dev/$kname...\n";
    &umount();
} else {
    print "/dev/$kname is NOT mounted.\n";
}

my $cmd = "/sbin/blockdev --getsz /dev/$kname";
my $card_size = `$cmd`;
chomp($card_size);
$card_size *= 512;

print "Kernel name = $kname\n";
print "Chapter file = $chapfile\n";
print "Card size = $card_size bytes\n";

if ($kname eq "sda") {
    die "Cannot use system hard drive (sda)!!!";
}

open FILE, $chapfile or die $!;

my $totalsize = 0;
my $numfiles = 0;
my $availablespace = 0;
my $result;

while (<FILE>) {
    chomp;
    if (-f $_) {
        $totalsize += (-s $_);
        $numfiles++;
    }
}

print "Total size of all files: $totalsize bytes\n";

if (-b "/dev/$kname") {
    $result = `/bin/sudo /bin/mkdir /mnt/$kname`;
    print $result;

    $result = `/bin/sudo /bin/mount /dev/$kname /mnt/$kname`;
    print $result;

    print "\nVerifying files on microSD card...\n";

    my $starttime = time;

    open my $result_fh, "/bin/sudo /usr/local/bin/makemenu -c $chapfile -m /mnt/$kname -v|";
    while (<$result_fh>) {
        print $_;
    }
    close $result_fh;
    print "\n";

    my $endtime = time;

    &umount();

    $result = `/bin/sudo /bin/rmdir /mnt/$kname`;
    print $result;

    my $readspeed;
    my $timediff = $endtime - $starttime;
    print "Time difference is $timediff\n";
    if ($timediff > 0) { $readspeed = $totalsize/$timediff/1024/1024; }
    print "Read $totalsize bytes in $timediff seconds\n";
    printf("Average read speed: %.1f MB/s\n", $readspeed);

} else {
    print "/dev/$kname is NOT a valid block special file!\n";
}


sub umount {
    $result = `/bin/sudo /bin/umount /dev/$kname`;
    print $result;
    if ($?) {
        print "Failed to unmount /dev/$kname... will try again in 10 sec...\n";
        sleep 10;
        $result = `/bin/sudo /bin/umount /dev/$kname`;
        print $result;
        if ($?) {
            print "Failed to unmount /dev/$kname... QUITTING!\n";
            exit;
        } else {
            print "Managed to unmount /dev/$kname on the second attempt\n";
        }
    } else {
        print "Managed to unmount /dev/$kname on the first attempt\n";
    }
}

#close STDOUT;
#close STDERR;
